### ISSUE TITLE
Laravel 5.2 Compatibility issue

### ISSUE THREAD

**Issue by HekmatBeigverdi** [Kryptonit3/Counter#3]
Facades and alias added to config/app.php works properly in laravel 5.1 but this is not work with 5.2 and The following error occur:
FatalErrorException in CounterServiceProvider.php line 18: Call to undefined method Illuminate\Foundation\Application::bindShared()

**Comment by HekmatBeigverdi** [comment]
I follow this link:
https://laracasts.com/discuss/channels/laravel/call-to-undefined-method-illuminatefoundationapplicationbindshared

i do 

bindShared has been renamed to $app->singleton()

but this error show:Method filter does not exist.

**Comment by Kryptonit3-zz** [comment]
@HekmatFavid update your `composer.json` to `"kryptonit3/counter": "5.2.*"` and let me know if that fixes it.

**Comment by HekmatBeigverdi** [comment]
Thank you
following problem occures !!
![capture](https://cloud.githubusercontent.com/assets/16886775/12573519/439c5308-c40f-11e5-953c-b9bd85a28f89.PNG)

**Comment by Kryptonit3-zz** [comment]
the issue is this: https://github.com/Kryptonit3/Counter/blob/3380b3121380008f44007e57f44240a7915dc933/src/routes.php

I will need to figure out a way to do this with middleware instead of `Route::filter` when I can find some time.

**Comment by Kryptonit3-zz** [comment]
@HekmatFavid  run a `composer update`. I added a change to a new release `5.2.2`. As long as your composer.json has `5.2.*` a `composer update` should pull in change. Let me know if that fixes it.

**Comment by HekmatBeigverdi** [comment]
:clap:  :clap: It work's Properly.  :clap:  :clap:
I really appreciate your help
