### ISSUE TITLE
installation issue - @php artisan package:discover --ansi

### ISSUE THREAD

**Issue by birhann** [Kryptonit3/Counter#39]
I'm not sure you are still looking at this package but i have a problem with the installation.
After the:  composer require kryptonit3/counter:5.2.*

![larasad](https://user-images.githubusercontent.com/26721459/91082931-17d89c80-e652-11ea-8217-81b2691e538d.PNG)

And the package doesn't work as it used to. Maybe the main problem is with the composer but i have no idea. i am new at the laravel packages actually. Do you have any idea what to do ??

**Comment by birhann** [comment]
Sorry, my bad. There is no php tag in routes.php, how can`t i saw that.  I feel like an idiot :) by the way @hemal-digiflux solved in the last pull request, you can accept again 👍

**Comment by hemal-digiflux** [comment]
Yes. Please merge the last PR.
