### ISSUE TITLE
Deleting the page views registrations

### ISSUE THREAD

**Issue by stoyangenchev** [Kryptonit3/Counter#8]
Still using the package. So far, so good. Just came to a point where I need to delete page views registrations when page with content is deleted, because they are more than 10 000 views per page and optimization is welcome from everywhere.

So what I am saying is, is there a built in functionality to do that?

**Comment by Kryptonit3-zz** [comment]
not currently but I will add it.

**Comment by stoyangenchev** [comment]
Okay, looking forward to it.
